### ISSUE TITLE
tagcloud with random order is not working

### ISSUE THREAD

**Issue by MacKP** [psi-4ward/news4ward_tags#19]
Hi psi ^^
I don't know if it would work in an new Installation. I have here an update from contao 2.11 to 3.5.15 (now everything installed via Composer).
The one thing that isn't working is the random order in the Tagcloud. I hav over 25 Items in the Tag-Cloud and I just wan't to display 25 with random...
When you need more Inforamation just ask (also in IRC or Mumble).

regards

**Comment by frontendschlampe** [comment]
We will make an update to 3.5.x next week if you can wait so long?

**Comment by backbone87** [comment]
code checks for news4ward_tags_random, but the field is called news4ward_tags_shuffle

**Comment by MacKP** [comment]
OK, now we are clear. I have an version without the feature 'random'. 'shuffle' was in the old days like 'random' but isn't anymore (was probably an bug ore someone changed the code...)

random is not tagged at the moment (will be next week maybe).

regards and thx @backbone87
